@host = http://localhost:8080
@token = dev-push-token-change-before-production

### Health Check
GET {{host}}/health

### Push Message
POST {{host}}/push
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "targets": ["news:*"],
  "message": {
    "type": "alert",
    "content": "hello"
  }
}